Marks = []

f1 = input("Enter Marks Here: ")
Marks.append(f1)
f2 = input("Enter Marks Here: ")
Marks.append(f2)
f3 = input("Enter Marks Here: ")
Marks.append(f3)
f4 = input("Enter Marks Here: ")
Marks.append(f4)
f5 = input("Enter Marks Here: ")
Marks.append(f5)
f6 = input("Enter Marks Here: ")
Marks.append(f6)
f7 = input("Enter Marks Here: ")
Marks.append(f7)
print(Marks)

Marks.sort()
print(Marks)